import { pathToFileURL } from 'node:url';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { mkdirSync } from 'node:fs';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const outDir = resolve(root, '../_demo_shots/ghost-mvp');
mkdirSync(outDir, { recursive: true });

const { chromium } = await import(pathToFileURL(resolve(root, '../game/web/node_modules/playwright/index.mjs')).href);
const { createAppServer } = await import(pathToFileURL(resolve(root, 'server.mjs')).href);

const server = createAppServer({ env: {} });
await new Promise((r, j) => { server.once('error', j); server.listen(0, '127.0.0.1', r); });
const url = `http://127.0.0.1:${server.address().port}`;
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
const shot = (name) => page.screenshot({ path: resolve(outDir, `${name}.png`) });
const closePanel = () => page.locator('[data-action="close"]').first().click();

await page.goto(url, { waitUntil: 'networkidle' });
await shot('01-intro');
await page.getByRole('button', { name: '跳过引导' }).click();
await shot('02-room-start');
await page.getByTestId('object-report').click();
await shot('03-inspect-panel');
await closePanel();
await page.locator('.hotspot[data-id="father"]').click(); await closePanel();
await page.locator('.hotspot[data-id="lin"]').click(); await closePanel();
await page.getByTestId('view-replay').click();
await shot('04-replay-1910');
await page.getByTestId('replay-1913').click();
await shot('05-replay-1913');
await page.getByTestId('object-plate').click();
await shot('06-plate-m05');
await closePanel();
await page.getByTestId('open-belief').click();
await shot('07-belief-chain');
await page.getByTestId('inference-worth').click();
await page.getByRole('button', { name: '不能这样推出' }).click();
await page.getByTestId('evidence-M01').click();
await page.getByTestId('evidence-M03').click();
await page.getByRole('button', { name: '用自己的话说' }).click();
await page.getByTestId('reconstruction-input').fill('即使这次没有达到期待，也不能说明我不值得被爱。');
await shot('08-reasoning');
await page.getByRole('button', { name: '确认这表达了我的意思' }).click();
await page.getByTestId('outcome-express').waitFor();
await shot('09-reconstruct');
await page.getByTestId('outcome-express').click();
await page.getByTestId('preview').click();
await shot('10-preview');
await page.getByTestId('confirm-reconstruction').click();
await page.getByTestId('move-table').waitFor();
await shot('11-act-room');
await page.getByTestId('move-table').click();
await page.getByTestId('act-express').click();
await page.getByRole('heading', { name: '林澈把那句话说完了' }).waitFor();
await shot('12-result-A');

await browser.close();
await new Promise((r) => server.close(r));
console.log(`[shots] saved to ${outDir}`);
